# Введение в питон

## ДЗ 4

### Задача 1

In [71]:
number = int(input())
if number == 0:
    print("0")
else:
    ans = ""
    while number > 0:
        ans = str(number % 2) + ans
        number //= 2
print(ans)

 255


11111111


### Задача 2

In [76]:
number = int(input())

def foo(n):
  cnt = 0
  while n > 0:
    if n % 2 == 0:
      cnt += 1
    n //= 2
  return cnt



count, sum = 0, 0
while number != 0:
  if foo(number) == 3:
    count, sum = count + 1, sum + number
      
  number = int(input())
print(count, sum)

 0


0 0


### Задача 3

In [78]:
tmp = str(input()).split()
b = float(tmp[0])
q = float(tmp[1])
N = int(tmp[2])

ans = b  *(1 - q**N) / (1 - q)

print(f"{ans:.3f}")

 1 2 3


7.000


### Задача 4

In [81]:
n = int(input())
ans = None
for i in range(n):
    tmp = min(list(map(float, input().split())))

    ans = tmp if ans is None else max(ans, tmp)
    
print(f"{ans:.3f}")

 3
 -10 9 3
 0 6
 3 6 9 2


2.000


### Задача 5

In [65]:
limit, N = str(input()).split()
limit, N = int(limit), int(N)

ans = 0
for _ in range(N):
    tmp = [[int(i.split('/')[0]), int(i.split('/')[1])] for i in str(input()).split()]
    tmp = [i[0]* i[1] for i in tmp if i[0] <= limit]
    ans += 0 if not tmp else min(tmp)
    
print(ans)

 100 4
 120/10 80/20
 120/10 110/10 130/10 120/15
 100/10 110/15 95/25
 90/10 80/20 85/15


3500


## ДЗ 5

### Задача 1

In [88]:
start, stop, step = map(int, input().split())
ans = list(map(int, input().split()))

for i in range(start, stop, step):
    ans[i] = i  

print(ans)

 1 5 2
 10 20 30 40 50 60


[10, 1, 30, 3, 50, 60]


### Задача 2

In [102]:
children = []
with open("weights.txt", 'r') as f:
    for line in f:
        children.append(line.split())

children = sorted(children, reverse=True, key=lambda x: float(x[1]))

ans = children[::2] + children[1::2]

with open('team.txt', 'w') as f:
    for weight, name in ans:
        f.write(f"{name} {weight}\n")

### Задача 3

In [20]:
with open("poe_unpublished.txt", 'r') as f:
    text = f.read()

tmp = text.split("\n")
tmp.sort(key=lambda x: len(x.split()))
tmp = [sorted(i.split(), key=lambda x: len(x)) for i in tmp]

with open('poe_decode_attempt.txt', 'w') as f:
    for line in tmp:
        f.write(" ".join(line) + "\n")

In [22]:
!cat poe_unpublished.txt

I was angry with my friend
I told my wrath my wrath did end
I was angry with my foe
I told it not my wrath did grow

In [21]:
!cat poe_decode_attempt.txt

I my was with angry friend
I my was foe with angry
I my my did end told wrath wrath
I it my not did told grow wrath


### Задача 4

In [44]:
with open("med_research.txt", 'r') as f:
    matrix = [i.split() for i in f.read().splitlines()]

n, m = len(matrix), len(matrix[0])
ans = [[0 for i in range(n)] for j in range(m)]

for i in range(n):
    for j in range(m):
        ans[j][i] = matrix[i][j]

with open('output.txt', 'w') as f:
    for line in ans:
        f.write(" ".join(line) + "\n")

In [45]:
!cat med_research.txt

1 2 3 4 5
6 7 8 9 10

In [46]:
!cat output.txt

1 6
2 7
3 8
4 9
5 10


### Задача 5

In [68]:
with open("the_calls.txt", 'r') as f:
    calls = [i.split('\t') for i in f.read().splitlines()]

A = sorted([i for i in calls if i[2] == 'A'], key=lambda x: int(x[1]), reverse=True)
B = sorted([i for i in calls if i[2] == 'B'], key=lambda x: int(x[1]), reverse=True)

ans = A + B
with open('calls.txt', 'w') as f:
    for line in ans:
        f.write("\t".join(line) + "\n")

In [69]:
!cat the_calls.txt

2021.12.12	3	B	+79090329400
2019.10.03	18	A	+79999995454
2020.05.04	13	B	+72352452532
2020.05.04	4	A	+79023987567

In [70]:
!cat calls.txt

2019.10.03	18	A	+79999995454
2020.05.04	4	A	+79023987567
2020.05.04	13	B	+72352452532
2021.12.12	3	B	+79090329400


## ДЗ 6

### Задача 4

In [35]:
d ={}
for i in str(input()):
    if i in d:
        d[i] += 1
    else:
        d[i] = 1

print(min([int(i[0]) for i in d.items() if i[1] == min(d.values())]))

 2021


0


### Задача 5

In [38]:
animals = set()
with open('input.txt', 'r') as file:
    for line in file:
        parts = line.strip().split()
        animals.add(parts[1])

for animal in sorted(animals, key=len):
    print(animal)

leopard
orangutan


### Задача 6

In [56]:
animals = {}
with open('input.txt', 'r') as file:
    for line in file:
        parts = line.strip().split()
        if parts[1] in animals:
            animals[parts[1]].add(parts[2])
        else:
            animals[parts[1]] = set([parts[2]])

flag = 0
for animal, gender in animals.items():
    if ('female' in gender) and ('male' in gender):
        print(animal)
        flag = 1
        
if not flag:
    print(0)

0


### Задача 7

In [65]:
animals = {}
with open('input.txt', 'r') as file:
    for line in file:
        parts = line.split()
        if parts[1] in animals:
            animals[parts[1]] += 1
        else:
            animals[parts[1]] = 1
            
tmp = sorted(sorted_animals.items(), key=lambda x: x[1], reverse=True)
for i in tmp:
    print(i[0], "-", i[1])

dog - 2
cat - 1


### Задача 8

In [82]:
animals = {}
with open('input.txt', 'r') as file:
    for line in file:
        parts = line.strip().split()
        if parts[1] in animals:
            animals[parts[1]].append(parts[0])
        else:
            animals[parts[1]] = [parts[0]]
tmp = sorted(animals.items(), key=lambda x: len(x[0]))
for i in tmp:
    print(i[0], ": ", ", ".join(sorted(i[1])), sep="")

dog: 0003, 0043
lion: 0042


## ДЗ 7

### Задача 1

In [ ]:
27

### Задача 2

In [3]:
def calculate_clients(day):
    return int(np.exp(np.sin(day / 100)* (day / 10)) * 20)

# Рассчитаем количество клиентов для 18 числа
clients_on_18th = calculate_clients(18)
print(clients_on_18th)

27


### Задача 3

In [9]:
import numpy as np

N=int(input())

tmp = np.arange(1, N + 1)
ans = tmp.astype(str) 

ans[tmp % 3 == 0] = 'Fizz'
ans[tmp % 5 == 0] = 'Buzz' 
ans[(tmp % 3 == 0) & (tmp % 5 == 0)] = 'FizzBuzz' 

print(' '.join(ans))

 15


1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz


### Задача 4

In [36]:
import numpy as np

with open('input.txt', 'r') as file:
    a1, a2, num = list(map(lambda x: float(x.strip()), list(file)))
  
expectation = np.linspace(a1, a2, int(num))

fact = expected_profit.copy()

fact[np.arange(num, dtype=np.int64) %7 == 0] /= 3
fact[np.arange(num, dtype=np.int64) %7 == 4] *= 2

with open('output.txt', 'w') as file:
    for num in fact:
        file.write(f"{num:.2f}\n")

### Задача 5

In [ ]:
import math

f = lambda x: math.sin(math.tan(1 + x / 1000))

def bisec(l, r, tol=1e-6):
    while (r - l) > 2*tol:
        mid = (l + r) / 2 
        if f(l) * f(mid) < 0:
            r = mid  
        else:
            l = mid  
    return (l + r) / 2 


N, res = int(input()), []

for i in range(N):
    a, b = list(map(float, input().split()))
    ans = bisec(a, b)
    res.append(f"{ans:.6F}")

for result in res:
    print(result)

## ДЗ 8

### Задача 1

In [4]:
import numpy as np

with open('input.txt', 'r') as file:
    m = [list(map(float, l.split())) for l in file]

print(np.array(matrix).T)

[[ 5.5  8.1 84.9]
 [45.2 80.5 70.2]]


### Задача 2

In [ ]:
import numpy as np

with open('input.txt', 'r') as file:
    data = np.array(list(map(int, file.read().split())))

print(f"{np.median(data):.2f} {np.mean(data):.2f} {np.std(data):.2f}")

### Задача 3

In [6]:
import numpy as np

logs = np.loadtxt('input.csv', delimiter=',')
logs[::2, 1::2] /= 2
logs[1::2, ::2] /= 2
np.savetxt('output.csv', logs, delimiter=',', fmt='%g')

### Задача 4

In [12]:
import numpy as np

data = np.genfromtxt('input.csv', delimiter=',', dtype=int)

with open('output.txt', 'w') as f:
    f.write(str(np.argmax(data.sum(axis=0)) + 1))

### Задача 5

In [14]:
import numpy as np

data = np.loadtxt("input.csv", delimiter=',')

std_deviations = np.std(data, axis=1)

if np.sum(std_deviations <= 4) > np.sum(std_deviations > 4):
    print(1)
else:
    print(2)

2


### Задача 6

In [17]:
import numpy as np
data = np.loadtxt('input.csv', delimiter=',', dtype=int)
data[0, :] = (np.mean(data, axis=0)*1.5).astype(np.int32)
np.savetxt('output.csv', data, delimiter=',', fmt='%d')

## ДЗ 9

### Задача 1

In [32]:
import itertools

permutations = list(itertools.product([1, 0], repeat=3))

ans = []
for permutation in permutations:
    if (not permutation[0] and permutation[1] and not permutation[2]) or \
       (not permutation[0] and permutation[1] and permutation[2]) or \
       (permutation[0] and not permutation[1] and not permutation[2]):
        ans.append(permutation)

ans.sort(key=lambda permutation: int(''.join(np.array(permutation, dtype=str)), 2))

for permutation in ans:
    print(' '.join('True' if value else 'False' for value in permutation))

False True False
False True True
True False False


### Задача 2

In [34]:
import pandas as pd

df = pd.read_csv('input.csv', header=None)
print(df.mean(axis=0).idxmin() + 1)

16


### Задача 3

* data[(data.weekdays == 'Thu') & (data.prices > 2000000)]

* data.query('weekdays == "Thu" and prices > 2000000')

### Задача 4

In [60]:
import pandas as pd

data = pd.read_csv('input.csv')
print(((data.a + data.b > data.c) & (data.b + data.c > data.a) & (data.c + data.a > data.b)).sum(axis=0))

4


### Задача 5

In [65]:
import pandas as pd

df = pd.read_csv("input.csv")
print(df.columns[df.mean().values.argmax()])

Вишенка


### Задача 6

In [75]:
import pandas as pd

data = pd.read_csv('input.csv', index_col=0)
if data.sum().sum() >= 8000000:
    print(1, data.sum().idxmax())
else:
    print(0, data.sum().idxmax())

1 Мыло.ру


## ДЗ 10

### Задача 1

In [83]:
import pandas as pd

df = (
    pd.read_csv("input.csv")
    .dropna(subset=["name"])
    .assign(score = lambda x: x.score.fillna(x.score.mean()))
)

df.to_csv("output.csv")

### Задача 2

In [87]:
import pandas as pd

df = pd.DataFrame(np.array([["login3", 2, 5, 5],
                  ["login1", 2, 5, 5],
                  ["login4", 2, 5, 5],
                  ["login5", 2, 5, 5]]), columns=["login", "score4", "score5", "score6"])

df.index +=1

df.login.loc[2:3]

2    login1
3    login4
Name: login, dtype: object

### Задача 3

In [96]:
import pandas as pd

df = pd.read_csv('input.csv')
df['temperature_f'] = df['temperature_c'].apply(lambda x: round((x*9/5) + 32))
df.to_csv('output.csv')

### Задача 4

In [158]:
import pandas as pd

df = pd.read_csv('input.csv')

if not df.empty and 'ID' in df.columns: 

    df['Объем груза'] = df.apply(lambda row: row['Объем груза'] if row['Тип операции'] == 'Привоз' else -row['Объем груза'], axis=1)

    ans = (
        df.groupby('Фамилия водителя')['Объем груза']
        .sum()
        .reset_index()
        .sort_values(by=['Объем груза', 'Фамилия водителя'], ascending=[False, True])
    )
    
    ans.to_csv('output.csv', index=False, encoding='utf8')
else:

    df_empty = pd.DataFrame(columns=['Фамилия водителя', 'Объем груза'])
    df_empty.to_csv('output.csv', index=False, encoding='utf8')

### Задача 5

In [155]:
import pandas as pd

df = (
    pd.read_csv('input.csv')
    .assign(tmp=lambda x: x["Город отправления"] + x["Город прибытия"])
    .rename(columns={"tmp": "Уникальных маршрутов"})
)

(
    df[["Номер борта", "Уникальных маршрутов"]]
    .groupby(["Номер борта"])
    .nunique()
    .reset_index()
    .sort_values(["Уникальных маршрутов", 'Номер борта'], ascending=[False, True])
    .to_csv("output.csv", encoding="utf8", index=False)
)

### Задача 6

inner

## ДЗ 11

### Задача 1

In [15]:
class Incapsulator:
    def __init__(self, value = 0):
        self.val_inner = value

    def set_value(self, val):
        self.val_inner = val

    def get_value(self):
        return self.val_inner

In [16]:
a = Incapsulator()
assert a.get_value() == 0

a.set_value(5.0)
assert a.get_value() == 5

a.set_value(-1.0)
assert a.get_value() == -1

### Задача 2

In [24]:
class Student:
    def __init__(self, name, age):
        self.name, self.age = name, float(age)

    def __repr__(self):
        return f"Student({self.name}, {self.age})"

    def __str__(self):
        return f"Student {self.name} of age {self.age}"

In [25]:
a = Student()

TypeError: Student.__init__() missing 2 required positional arguments: 'name' and 'age'

In [26]:
a = Student("Ivan", 18)
a

Student(Ivan, 18.0)

In [27]:
print(a)

Student Ivan of age 18.0


In [28]:
a = Student("Ivan", 18.0)
a

Student(Ivan, 18.0)

In [29]:
print(a)

Student Ivan of age 18.0


### Задача 3

In [59]:
class SpyingNumber:
    global_counter = 0

    def __init__(self, value):
        self.value = value

    @staticmethod
    def get_global_counter():
        return SpyingNumber.global_counter

    @staticmethod
    def reset_global_counter():
        SpyingNumber.global_counter = 0

    def add(self, other):
        if isinstance(other, (int, float)):
            other = SpyingNumber(other)
        SpyingNumber.global_counter += 1
        return SpyingNumber(self.value + other.value)

    def sub(self, other):
        if isinstance(other, (int, float)):
            other = SpyingNumber(other)
        SpyingNumber.global_counter += 1
        return SpyingNumber(self.value - other.value)

    def mul(self, other):
        if isinstance(other, (int, float)):
            other = SpyingNumber(other)
        SpyingNumber.global_counter += 1
        return SpyingNumber(self.value * other.value)

    def truediv(self, other):
        if isinstance(other, (int, float)):
            other = SpyingNumber(other)
        SpyingNumber.global_counter += 1
        return SpyingNumber(self.value / other.value)

    def __repr__(self):
        return f"SpyingNumber({self.value})"

    def __str__(self):
        return str(self.value)

    def __add__(self, other):
        return self.add(other)

    def __sub__(self, other):
        return self.sub(other)

    def __mul__(self, other):
        return self.mul(other)

    def __truediv__(self, other):
        return self.truediv(other)


In [60]:
assert SpyingNumber.get_global_counter() == 0
x = SpyingNumber(10)
print(x)

10


In [61]:
x = x + 10

In [62]:
x

SpyingNumber(20)

In [63]:
x.get_global_counter()

1

In [64]:
y = x * SpyingNumber(2.5)

In [65]:
y

SpyingNumber(50.0)

In [66]:
x = x / 2

In [67]:
y.get_global_counter()

3

In [68]:
y - 50

SpyingNumber(0.0)

In [69]:
SpyingNumber.get_global_counter()

4

In [70]:
print(SpyingNumber.get_global_counter())

4


### Задача 4

In [114]:
class GeomRangeIterator:
    def __init__(self, start, stop, step):
        self.current, self.stop, self.step = start, stop,step

    def __next__(self):
        if self.current >= self.stop:
            raise StopIteration
        ans = self.current
        self.current *= self.step
        return ans


class GeomRange:
    def __init__(self, *args):
        if len(args) == 1:
            self.start, self.stop, self.step = 1, args[0], 2
        elif len(args) == 2:
            self.start, self.stop, self.step = args[0], args[1], 2
        elif len(args) == 3:
            self.start, self.stop, self.step = args[0], args[1], args[2]
        else:
            raise Exception

    def __getitem__(self, n):
        val = self.start * (self.step ** n)
        if val >= self.stop:
            raise IndexError("index is out of the progression")
        return val

    def __iter__(self):
        return GeomRangeIterator(self.start, self.stop, self.step)

In [115]:
for x in GeomRange(1, 10, 2):
    print(x)

1
2
4
8


In [116]:
for x in GeomRange(1, 1, 2):
    print(x)

In [117]:
for x in GeomRange(1, 100, 3):
    print(x)

1
3
9
27
81


In [118]:
g = GeomRange(1, 100, 3)
next(g)

TypeError: 'GeomRange' object is not an iterator

In [106]:
it = iter(g)

In [112]:
next(it)

StopIteration: 

In [113]:
g = GeomRange(1, 100, 3)
assert g[0] == 1
assert g[1] == 3
assert g[2] == 9
assert g[3] == 27
assert g[4] == 81


# ML

## ДЗ 7

### Задача p1

In [6]:
import numpy as np

class sample(object):
    def __init__(self, X, n_subspace):
        self.idx_subspace = self.random_subspace(X, n_subspace)

    def __call__(self, X, y):
        return self.get_subsample(X, y, self.idx_subspace, self.bootstrap_sample(X))

    @staticmethod
    def bootstrap_sample(X):
        return np.unique(np.random.choice( len(X), size= len(X), replace=True))

    @staticmethod
    def random_subspace(X, n_subspace):
        return np.unique(np.random.choice(X.shape[1], size=n_subspace, replace=False))

    @staticmethod
    def get_subsample(X, y, idx_subspace, idx_obj):
        return X[idx_obj][:, idx_subspace], y[idx_obj]

In [9]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([1, 2, 3])
s = sample(X, 2)

bootstrap_indices = s.bootstrap_sample(X)
X_sampled, y_sampled = s.get_subsample(X, Y, s.idx_subspace, bootstrap_indices)

bootstrap_indices, s.idx_subspace, X_sampled, y_sampled

(array([1, 2]),
 array([1, 2]),
 array([[5, 6],
        [8, 9]]),
 array([2, 3]))

In [ ]:
# Дх